# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x111416ff
bordercolor = 0x8c9198ff
focuscolor = 0x93ccffff
maximizescreencolor = 0xb8c8daff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xd2bfe7ff
globalcolor = 0x004b73ff
overlaycolor = 0x394857ff
