# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x191114ff
bordercolor = 0x9d8c91ff
dropcolor = 0xffb0cf80
splitcolor = 0xf1bb97ff
focuscolor = 0xffb0cfff
maximizescreencolor = 0xe1bdc9ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xf1bb97ff
globalcolor = 0x6e334eff
overlaycolor = 0x593f49ff
jump_label_decorate_fg_color = 0xeedfe2ff
jump_label_decorate_bg_color = 0x30282bff
jump_label_decorate_focus_fg_color = 0x531d37ff
jump_label_decorate_focus_bg_color = 0xffb0cfff
jump_label_decorate_border_color = 0x9d8c91ff
