windowrule=title:Picture in picture,isfloating:1
windowrule=title:Bitwarden,appid:chrome-nngceckbapebfimnlniiiahkandclblb-Default,isfloating:1

windowrule=appid:kiro,scroller_proportion:1.0
windowrule=appid:dev.zed.Zed,scroller_proportion:1.0
windowrule=appid:helium,scroller_proportion:1.0
