[tools]
lazydocker = "latest"
node = "20.19.3"
rg = "latest"
prettier = "latest"
lazygit = "latest"
bat = "latest"
eza = "latest"
zoxide = "latest"
fd = "latest"
pnpm = "latest"
yarn = "latest"
fastfetch = "latest"
jq = "latest"
tlrc = "latest"
"ubi:junegunn/fzf" = "latest"
python = "latest"
tmux = "latest"
zellij = "latest"
