-- Generated by Helios (Themes.qml) — do not edit by hand

local active = "rgb(F0A868)"
local inactive = "rgb(282331)"
local locked = "rgb(E5707E)"
local text_active = "rgb(2C1C0F)"
local text_inactive = "rgb(EAE6F0)"

local function apply_theme()
    hl.config({
        general = {
            col = {
                active_border = active,
                inactive_border = inactive,
            },
        },
        group = {
            col = {
                border_active = active,
                border_inactive = inactive,
                border_locked_active = locked,
                border_locked_inactive = inactive,
            },

            groupbar = {
                gradients = true,
                col = {
                    active = active,
                    inactive = inactive,
                    locked_active = locked,
                    locked_inactive = inactive,
                },
                text_color = text_active,
                text_color_inactive = text_inactive,
                text_color_locked_active = text_active,
                text_color_locked_inactive = text_inactive,
            },
        },
    })
end

return {
    apply_theme = apply_theme
}
