local utils = dofile(os.getenv("HOME") .. "/.config/hypr/utils.lua")

hl.monitor({
  output = "DP-1",
  disabled = false,
  mode = "3440x1440@144.00Hz",
  position = "0x0",
  scale = 1.25,
  vrr = 3,
  cm = "srgb",
  bitdepth = 10
})

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

hl.gesture({
  fingers = 3,
  direction = "horizontal",
  action = "workspace"
})

require("modules.env")
require("modules.autostart")
require("modules.general")
require("modules.input")
require("modules.misc")
require("modules.decorations")
require("modules.binds")
require("modules.window_rules")
require("modules.layer_rules")
require("modules.animations")
utils.safe_load("plugins/init")

-- For Noctalia Color templates
-- require("noctalia").apply_theme()

-- For Helios Color templates (generated by the qml-shell Themes service)
pcall(function() require("helios").apply_theme() end)
require("helios-binds")
