bind=SUPER+ALT,l,spawn,dms ipc call lock lock
bind=SUPER,comma,spawn,dms ipc call settings focusOrToggle
bind=SUPER,m,spawn,dms ipc call processlist focusOrToggle
bind=SUPER,n,spawn,dms ipc call notifications toggle
bind=SUPER,space,spawn,dms ipc call spotlight toggle
bind=SUPER,v,spawn,dms ipc call clipboard toggle
bind=SUPER,y,spawn,dms ipc call dankdash wallpaper
bind=none,XF86AudioLowerVolume,spawn,dms ipc call audio decrement 3
bind=none,XF86AudioMute,spawn,dms ipc call audio mute
bind=none,XF86AudioRaiseVolume,spawn,dms ipc call audio increment 3
bind=none,XF86MonBrightnessDown,spawn,dms ipc call brightness decrement 5
bind=none,XF86MonBrightnessUp,spawn,dms ipc call brightness increment 5
bind=SUPER+ALT,x,spawn,dms ipc call powermenu toggle
