[tools]
node = "22"
starship = "latest"
pnpm = "latest"
eza = "latest"
zoxide = "latest"
fzf = "latest"
fd = "latest"
ripgrep = "latest"
atuin = "latest"
usage = "latest"
rust = "latest"
graalvm = "21"
