[tools]
node = "22"
starship = "latest"
pnpm = "latest"
eza = "latest"
zoxide = "latest"
fzf = "latest"
fd = "latest"
ripgrep = "latest"
atuin = "latest"
usage = "latest"
rust = "latest"
java = "graalvm-community-25.0.2"
lazygit = "latest"
resvg = "latest"
claude-code = "latest"
codex = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
